# Project: project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = mall.o queue.o
LINKOBJ  = mall.o queue.o
LIBS     = -L"C:/Portable/Dev-Cpp/MinGW64/lib" -L"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Portable/Dev-Cpp/MinGW64/include" -I"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Portable/Dev-Cpp/MinGW64/include" -I"C:/Portable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Portable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) -Og -g3 -std=c11
CFLAGS   = $(INCS) -Og -g3 -std=c11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

mall.o: mall.c
	$(CC) -c mall.c -o mall.o $(CFLAGS)

queue.o: queue.c
	$(CC) -c queue.c -o queue.o $(CFLAGS)
